# Generated by Django 4.1.7 on 2023-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAirPlaneTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullnames', models.CharField(max_length=100)),
                ('PassportDetails', models.CharField(default=0, max_length=100)),
                ('Traveltime', models.DateField()),
                ('FlightAirline', models.CharField(max_length=200)),
                ('FlightClass', models.CharField(max_length=200)),
                ('PaymentInformation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullnames', models.CharField(max_length=100)),
                ('HotelName', models.CharField(max_length=200)),
                ('CheckIn', models.DateField()),
                ('CheckOut', models.DateField()),
                ('NumberOfPeaple', models.IntegerField(default=0)),
                ('NumberOfRooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullnames', models.CharField(default=0, max_length=200)),
                ('TourDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UberReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullnames', models.CharField(default=0, max_length=200)),
                ('PickUpLocation', models.CharField(default=0, max_length=200)),
                ('DropoffLocation', models.CharField(default=0, max_length=200)),
                ('pickUpDate', models.DateField()),
                ('pickUpTime', models.TimeField()),
            ],
        ),
    ]
